import http from 'node:http';import fs from 'node:fs';import {Service} from './service.mjs';
const root=process.env.AI_CODE_ROOT||process.cwd();const svc=new Service(root);const port=Number(process.env.PORT||4317);
const json=(res,x,status=200)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*'});res.end(JSON.stringify(x))};
const body=req=>new Promise((resolve,reject)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})});
const html=fs.readFileSync(new URL('../web/index.html',import.meta.url),'utf8');
const noBody=['GET','HEAD'].includes;const routeTask=/^\/api\/tasks\/([^/]+)\/(plan|approve|execute|review|repair|show|activity)$/;const routeRun=/^\/api\/runs\/([^/]+)\/events$/;
function sse(res){res.writeHead(200,{'content-type':'text/event-stream; charset=utf-8','cache-control':'no-cache','connection':'keep-alive','access-control-allow-origin':'*'});}
async function taskStream(req,res,id){sse(res);let last=0;let ticks=0;const timer=setInterval(()=>{try{const task=svc.task(id);const events=svc.store.listTaskEvents(id,last);for(const e of events){last=Math.max(last,e.id);res.write(`event: event\ndata: ${JSON.stringify(e)}\n\n`)}res.write(`event: state\ndata: ${JSON.stringify({task})}\n\n`);if(['COMPLETE','FAILED'].includes(task.state)||ticks++>360){clearInterval(timer);res.end()}}catch(e){clearInterval(timer);res.write(`event: error\ndata: ${JSON.stringify({error:e.message})}\n\n`);res.end()}},500);req.on('close',()=>clearInterval(timer));}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(html)}
if(u.pathname==='/api/overview')return json(res,{projects:svc.store.listProjects(),tasks:svc.store.listTasks(),runs:svc.store.listRuns(),providers:svc.store.listProviders(),models:svc.store.listModels(),automations:svc.store.listAutomations(),routing:svc.getRouting()});
if(u.pathname==='/api/projects'){if(req.method==='GET')return json(res,svc.store.listProjects());const b=await body(req);return json(res,svc.initProject(b.name,b.path),201)}
if(u.pathname==='/api/tasks'){if(req.method==='GET')return json(res,svc.store.listTasks(u.searchParams.get('projectId')));const b=await body(req);const t=svc.createTask(b.projectId,b.title);return json(res,svc.prepare(t.id),201)}
let m=u.pathname.match(routeTask);if(m){const id=m[1],op=m[2];if(op==='activity')return json(res,{task:svc.task(id),runs:svc.store.listRuns(id),events:svc.store.listTaskEvents(id)});if(op==='show')return json(res,{task:svc.task(id),runs:svc.store.listRuns(id)});const r=op==='plan'?await svc.plan(id):op==='approve'?svc.approve(id):op==='execute'?await svc.execute(id):op==='review'?await svc.review(id):await svc.repair(id);return json(res,r)}
if(u.pathname.match(/^\/api\/tasks\/([^/]+)\/stream$/)){return taskStream(req,res,u.pathname.split('/')[3])}
if(u.pathname==='/api/providers'){if(req.method==='GET')return json(res,{providers:svc.store.listProviders(),models:svc.store.listModels()});const b=await body(req);return json(res,svc.addProvider(b),201)}
const pm=u.pathname.match(/^\/api\/providers\/([^/]+)$/);if(pm){const id=pm[1];if(req.method==='PATCH')return json(res,svc.updateProvider(id,await body(req)));if(req.method==='DELETE'){if(svc.store.getProvider(id)?.kind==='mock')return json(res,{error:'Test provider cannot be deleted'},400);svc.store.updateProvider(id,{enabled:false});return json(res,svc.store.getProvider(id))}}
const pt=u.pathname.match(/^\/api\/providers\/([^/]+)\/test$/);if(pt){const b=await body(req);return json(res,await svc.testProvider(pt[1],b.modelId))}
const mm=u.pathname.match(/^\/api\/models\/([^/]+)$/);if(mm&&req.method==='PATCH')return json(res,svc.updateModel(mm[1],await body(req)));
if(u.pathname==='/api/routing'){if(req.method==='GET')return json(res,svc.getRouting());const b=await body(req);return json(res,svc.saveRouting(b));}
if(u.pathname==='/api/runs')return json(res,svc.store.listRuns(u.searchParams.get('taskId')));if(u.pathname.match(routeRun))return json(res,svc.store.listEvents(u.pathname.split('/')[3],Number(u.searchParams.get('after')||0)));
if(u.pathname==='/api/doctor')return json(res,await svc.doctor());
if(u.pathname==='/api/automations'){if(req.method==='GET')return json(res,svc.store.listAutomations());const b=await body(req);return json(res,svc.store.addAutomation({id:svc.store.id(),name:b.name,trigger:b.trigger,action:b.action,enabled:b.enabled!==false,createdAt:new Date().toISOString()}),201)}
const am=u.pathname.match(/^\/api\/automations\/([^/]+)$/);if(am&&req.method==='PATCH')return json(res,svc.store.updateAutomation(am[1],await body(req)));
if(u.pathname.startsWith('/api/webhooks/')){const trigger=u.pathname.split('/').pop();const b=await body(req);const matches=svc.store.listAutomations().filter(a=>a.enabled&&a.trigger===trigger);const created=[];for(const a of matches)if(b.projectId&&b.title)created.push(svc.prepare(svc.createTask(b.projectId,b.title).id));return json(res,{trigger,matched:matches.length,created})}
return json(res,{error:'not found'},404)}catch(e){return json(res,{error:e.message,stack:process.env.NODE_ENV==='development'?e.stack:undefined},400)}});
server.listen(port,()=>console.log(`AI Code Mission Control: http://localhost:${port}`));
