import fs from 'node:fs';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {Store} from './store.mjs';import {inspect,writeContext,buildContext} from './context.mjs';import {ensureGit,status,createWorktree,diff,changedFiles,protectAiCode} from './git.mjs';import {runAgent,classify} from './agents.mjs';import {loadPolicies,savePolicies} from './policy.mjs';
const exec=promisify(execFile);
const transitions={CREATED:['CONTEXT_READY'],CONTEXT_READY:['PLANNING'],PLANNING:['AWAITING_APPROVAL','FAILED'],AWAITING_APPROVAL:['APPROVED'],APPROVED:['IMPLEMENTING'],IMPLEMENTING:['TESTING','FAILED'],TESTING:['REVIEWING','FAILED'],REVIEWING:['COMPLETE','REPAIRING','FAILED'],REPAIRING:['TESTING','FAILED'],COMPLETE:[],FAILED:[]};
const capability={planner:'planning',implementer:'coding',reviewer:'review',repair:'repair'};
export class Service{
  constructor(root=process.cwd(),options={}){this.root=root;this.options=options;this.store=new Store(root);this.policies=loadPolicies(root)}
  transition(id,to){const t=this.task(id);if(!transitions[t.state]?.includes(to))throw new Error(`Invalid transition ${t.state} -> ${to}`);return this.store.updateTask(id,{state:to})}
  project(id){const p=this.store.getProject(id);if(!p)throw new Error('Project not found');return p}
  task(id){const t=this.store.getTask(id);if(!t)throw new Error('Task not found');return t}
  initProject(name,root){root=fs.realpathSync(root);ensureGit(root);protectAiCode(root);const existing=this.store.getProjectByPath(root);if(existing)return existing;const x=inspect(root);return this.store.addProject({id:this.store.id(),name,path:root,createdAt:new Date().toISOString(),language:x.language,framework:x.framework,commands:x.commands})}
  contextInit(projectId){const p=this.project(projectId);return writeContext(p)}
  createTask(projectId,title){this.project(projectId);const now=new Date().toISOString();return this.store.addTask({id:this.store.id(),projectId,title,state:'CREATED',createdAt:now,updatedAt:now})}
  prepare(id){this.transition(id,'CONTEXT_READY');this.store.updateTask(id,{context:JSON.stringify(buildContext(this.project(this.task(id).project_id),this.task(id)))});return this.transition(id,'PLANNING')}
  eligible(role,excluded=[]){const cap=capability[role];const policy=this.policies[role]||{};const pref=[...(policy.preferred||[]),...(policy.fallback||[])];const rows=[];for(const p of this.store.listProviders()){const routable=p.config?.routable!==false&&p.kind!=='mock';if(!p.enabled||!routable||excluded.includes(p.id))continue;for(const m of this.store.listModels(p.id)){if(!m.enabled||!m.capabilities.includes(cap))continue;const prefIndex=pref.indexOf(m.id)>=0?pref.indexOf(m.id):pref.indexOf(`${p.id}:${m.id}`);const providerIndex=pref.indexOf(p.id);const preference=prefIndex>=0?100000-prefIndex*1000:providerIndex>=0?50000-providerIndex*1000:0;const expected=(m.outputCostPerMTok??0)+(m.inputCostPerMTok??0)*0.25;const score=preference+m.quality*(policy.quality??1)+m.speed*(policy.speed??.3)-expected*(policy.cost??.1);rows.push({p,m,score})}}rows.sort((a,b)=>b.score-a.score);return rows}
  select(role,excluded=[]){const rows=this.eligible(role,excluded);if(rows[0])return rows[0];if(this.options.allowMock){for(const p of this.store.listProviders())if(p.kind==='mock'&&p.enabled&&!excluded.includes(p.id))for(const m of this.store.listModels(p.id))if(m.enabled&&m.capabilities.includes(capability[role]))return {p,m,score:0};}throw new Error(`No available model capable of ${role}`)}
  usageFrom(data){const u=data?.usage||data?.result?.usage||data?.message?.usage||data?.metadata?.usage;if(!u)return null;return {inputTokens:Number(u.input_tokens??u.inputTokens??u.prompt_tokens??0),outputTokens:Number(u.output_tokens??u.outputTokens??u.completion_tokens??0),cacheReadTokens:Number(u.cache_read_input_tokens??u.cache_read_tokens??0),cacheWriteTokens:Number(u.cache_creation_input_tokens??u.cache_write_tokens??0)}}
  extractText(data){if(typeof data==='string')return data;const c=data?.message?.content??data?.content??data?.result?.content;if(Array.isArray(c))return c.filter(x=>x?.type==='text').map(x=>x.text).join('\n');if(typeof c==='string')return c;if(typeof data?.result==='string')return data.result;return ''}
  price(model,usage,startedAt){const input=usage.inputTokens||0,output=usage.outputTokens||0,cacheRead=usage.cacheReadTokens||0,cacheWrite=usage.cacheWriteTokens||0;let i=model.inputCostPerMTok||0,o=model.outputCostPerMTok||0,cr=model.cacheReadCostPerMTok||0,cw=model.cacheWriteCostPerMTok||0,basis=model.billingMode==='api'?'published-api-rate':'list-price-equivalent';if(model.billingMode==='api'&&model.provider_id==='deepseek-claude-code'){const h=new Date(startedAt).getUTCHours(),day=new Date(startedAt).getUTCDay(),peak=day>=1&&day<=5&&((h>=1&&h<4)||(h>=6&&h<10));if(peak){i=model.peakInputCostPerMTok??i;o=model.peakOutputCostPerMTok??o;cr=model.peakCacheReadCostPerMTok??cr;cw=model.peakCacheWriteCostPerMTok??cw;basis='published-api-rate-peak'}else basis='published-api-rate-off-peak'}const cost=(input*i+output*o+cacheRead*cr+cacheWrite*cw)/1e6;return {cost,input,output,cacheRead,cacheWrite,basis}}
  async runRole(task,role,prompt,cwd,excluded=[]){let last;let previous=null;for(let attempt=0;attempt<8;attempt++){const {p,m}=this.select(role,excluded);const policy=this.policies[role]||{};const run=this.store.addRun({id:this.store.id(),taskId:task.id,role,providerId:p.id,modelId:m.id,status:'running',startedAt:new Date().toISOString(),fallbackFrom:previous});const started=Date.now();let sessionId=null,approxTokens=0,usage={inputTokens:0,outputTokens:0,cacheReadTokens:0,cacheWriteTokens:0};try{const context=buildContext(this.project(task.project_id),task);const full=`You are the ${role} agent in AI Code. The harness owns workflow state. Never claim a state transition occurred unless the harness performs it.\n\nTASK:\n${task.title}\n\nAPPROVED PLAN:\n${task.plan||'(planning stage)'}\n\nPROJECT CONTEXT:\n${JSON.stringify(context)}\n\nINSTRUCTIONS:\n${prompt}`;for await(const e of runAgent(p,m,{role,task,project:context.project,context,worktree:cwd,prompt:full,effort:policy.effort||p.config?.effort||undefined})){this.store.addEvent({runId:run.id,type:e.type,data:e.data});const u=this.usageFrom(e.data);if(u)usage={...usage,...u};const txt=this.extractText(e.data);approxTokens+=Math.ceil(txt.length/4);if(e.type==='completed'&&e.data?.sessionId)sessionId=e.data.sessionId}const total=usage.inputTokens+usage.outputTokens+usage.cacheReadTokens+usage.cacheWriteTokens||approxTokens;const priced=this.price(m,usage,new Date(run.started_at||run.startedAt||new Date()).toISOString());this.store.updateRun(run.id,{status:'succeeded',ended_at:new Date().toISOString(),tokens:total,cost:priced.cost,duration_ms:Date.now()-started,session_id:sessionId,input_tokens:usage.inputTokens,output_tokens:usage.outputTokens,cache_read_tokens:usage.cacheReadTokens,cache_write_tokens:usage.cacheWriteTokens,cost_basis:priced.basis});return {provider:p,model:m,runId:run.id,sessionId,usage,cost:priced.cost}}catch(e){last=e;this.store.updateRun(run.id,{status:'failed',ended_at:new Date().toISOString(),error:`${e.code||''} ${e.message}`,duration_ms:Date.now()-started});this.store.updateProvider(p.id,{config:{...p.config,lastError:e.code||classify(e.message),lastFailedAt:new Date().toISOString()}});excluded=[...excluded,p.id];previous=p.id;if(attempt<7)continue;throw e}}throw last}
  async plan(id){const t=this.task(id);if(t.state!=='PLANNING')throw new Error('Task must be in PLANNING');const p=this.project(t.project_id);const before=status(p.path);const result=await this.runRole(t,'planner','Produce ONLY a concrete implementation plan. Do not modify source files, create files, run mutating commands, commit, or execute implementation. Identify exact files, intended changes, tests, and verification commands. The harness will reject source changes.',p.path);const after=status(p.path);if(before!==after||changedFiles(p.path).some(x=>!x.includes('.ai-code'))){this.store.updateTask(id,{state:'FAILED'});throw new Error('PLANNING_VIOLATION: planner changed repository state')}const events=this.store.listEvents(result.runId);const text=events.map(e=>this.extractText(e.data)).filter(Boolean).join('\n');const plan=text||'No textual plan returned. Inspect the run events before approving.';this.store.updateTask(id,{plan});return this.transition(id,'AWAITING_APPROVAL')}
  approve(id){return this.transition(id,'APPROVED')}
  async execute(id){const t=this.task(id);if(t.state!=='APPROVED')throw new Error('Explicit approval required before execution');const p=this.project(t.project_id);const wt=createWorktree(p.path,t.id);this.store.updateTask(id,{worktree:wt.dir,branch:wt.branch,base_commit:wt.base});this.transition(id,'IMPLEMENTING');try{await this.runRole(t,'implementer','Implement the approved plan in this worktree. Do not change files outside the worktree. Do not alter AI Code task metadata.',wt.dir);this.transition(id,'TESTING');await this.test(t,wt.dir);this.transition(id,'REVIEWING');return this.review(id)}catch(e){this.store.updateTask(id,{state:'FAILED'});throw e}}
  async test(t,cwd){const cmd=this.project(t.project_id).commands.test;if(!cmd)return {skipped:true};try{await exec(cmd,{cwd,shell:true,maxBuffer:10*1024*1024});return {passed:true}}catch(e){throw new Error(`TEST_FAILED: ${e.stderr||e.stdout||e.message}`)}}
  async review(id){const t=this.task(id);if(t.state!=='REVIEWING')throw new Error('Task must be in REVIEWING');const d=diff(t.worktree);try{const r=await this.runRole(t,'reviewer',`Review this implementation independently. Return a clear verdict: PASS or FAIL. If FAIL, list concrete findings mapped to the approved plan and test evidence. Do not modify files.\n\nDIFF:\n${d}`,t.worktree);const text=this.store.listEvents(r.runId).map(e=>this.extractText(e.data)).filter(Boolean).join('\n');const fail=/\bfail(?:s|ed|ing|ures?)?\b/i.test(text)&&!/^\s*PASS\b/im.test(text);/* the verdict need not be the bare word: "the implementation fails to meet item 3" is as much a FAIL */if(fail){this.store.updateTask(id,{review:text});return this.transition(id,'REPAIRING')}this.store.updateTask(id,{review:text||'PASS'});return this.transition(id,'COMPLETE')}catch(e){this.store.updateTask(id,{review:String(e)});return this.transition(id,'REPAIRING')}}
  async repair(id){const t=this.task(id);if(t.state!=='REPAIRING')throw new Error('Task must be in REPAIRING');await this.runRole(t,'repair',`Repair the review findings in the worktree. Re-run relevant tests after fixing. Review findings:\n${t.review||'Review failed.'}`,t.worktree);this.transition(id,'TESTING');await this.test(this.task(id),t.worktree);this.transition(id,'REVIEWING');return this.review(id)}
  getRouting(){return this.policies}
  saveRouting(p){this.policies=savePolicies(this.root,p);return this.policies}
  addProvider(p){return this.store.addProvider(p)}
  addModel(m){this.store.addModel(m);return this.store.getModel(m.id)}
  updateProvider(id,p){return this.store.updateProvider(id,p)}
  updateModel(id,p){return this.store.updateModel(id,p)}
  async testProvider(id,modelId){const p=this.store.getProvider(id);if(!p)throw new Error('Provider not found');const models=this.store.listModels(id);const m=modelId?this.store.getModel(modelId):models.find(x=>x.enabled)||models[0];if(!m)throw new Error('Provider has no models');const run=this.store.addRun({id:this.store.id(),taskId:null,role:'provider-test',providerId:p.id,modelId:m.id,status:'running',startedAt:new Date().toISOString()});const started=Date.now();try{let text='';for await(const e of runAgent(p,m,{role:'provider-test',task:{id:'provider-test',title:'Provider connectivity test',project_id:null,plan:null},project:{path:process.cwd()},context:{},worktree:process.cwd(),prompt:'Reply with exactly OK. Do not use tools and do not modify files.',effort:p.config?.effort||'medium'})){this.store.addEvent({runId:run.id,type:e.type,data:e.data});const tx=this.extractText(e.data);if(tx)text+=tx}this.store.updateRun(run.id,{status:'succeeded',ended_at:new Date().toISOString(),duration_ms:Date.now()-started});return {ok:true,provider:p.name,model:m.name,response:text.slice(-1000),runId:run.id}}catch(e){this.store.updateRun(run.id,{status:'failed',ended_at:new Date().toISOString(),error:`${e.code||''} ${e.message}`,duration_ms:Date.now()-started});return {ok:false,provider:p.name,model:m.name,error:e.message,code:e.code||classify(e.message),runId:run.id}}}
  async doctor(){const checks=[];for(const cmd of ['git','node']){try{const {stdout}=await exec(cmd,['--version']);checks.push({name:cmd,ok:true,version:stdout.trim()})}catch{checks.push({name:cmd,ok:false})}}try{const {stdout}=await exec('claude',['--version']);checks.push({name:'claude',ok:true,version:stdout.trim()})}catch{checks.push({name:'claude',ok:false,requiredForRealAgents:true})}for(const p of this.store.listProviders().filter(x=>x.kind==='deepseek'))checks.push({name:p.name,ok:!!process.env[p.config.apiKeyEnv||'DEEPSEEK_API_KEY'],credential:p.config.apiKeyEnv||'DEEPSEEK_API_KEY'});return {checks}}
}
